export const MLP_MINIMUM_CHANCE = 0.75
export const MINIMUM_SITE_AGE = 7;
export const PHISH_HINTS = /(login|secure|account|bank|update|payment|password|verify|safety|security|confirm|personal|details|info|registration|signin|signout|logout|auth|authentication|credit|card|billing|verify|validate|login|subscribe|recovery|change|reset|profile|confirm|alert|alerting|security|transaction|check|alert|request|verification|secure|protection|encrypted|login|support|help|contact|customer|service|statement|confirm|receipt|purchase|sale|telegram|store|вход|аккаунт|безопасность|банковский|платеж|пароль|подтвердить|обновить|регистрировать|профиль|подтверждение|персональные|данные|оплата|восстановление|сменить|система|сервис|интернет-банкинг|деньги|платежи|покупка|счет|защита|перевод|транзакция|кредит|оплата|сумма|списание|пользователь|подписка|сигнализация|поддержка|служба|обслуживание|проверить|проверка|информация|контакт|клиент|ставка|возврат|активировать|обработка|финансовые|настройки|ошибка|активность|реквизиты|пожертвование|покупатель|оповещение|активировать|скачать)/;
export const shorteningServices = [
    "bit.ly",
    "goo.gl",
    "tinyurl",
    "ow.ly",
    "is.gd",
    "t.co",
    "adf.ly",
    "buff.ly",
    "lnkd.in",
    "v.gd",
    "shorte.st",
    "short.ly",
    "chng.it",
    "zmurl.com",
    "cli.re",
    "u.to",
    "srnk.net",
    "qr.net",
    "linktr.ee",
    "rebrand.ly",
    "cut.ly",
    "lil.ly",
    "link.tl",
    "fastly.me",
    "qrurl.com",
    "shortlink.co",
    "short.io",
    "bc.vc",
    "go2l.ink",
    "linkzip.net",
    "fave.co",
    "plink.in",
    "clicky.me",
    "linkbuck.com",
    "shrtfly.com",
    "2t.do",
    "qrphi.com",
    "tiny.cc",
    "x.co",
    "lnk.to",
    "s.id",
    "lnk.run",
    "cutt.ly",
    "ltt.ly",
    "shot.ly",
    "j.mp",
    "bit.do",
    "cuturl.in",
    "link.sh",
    "qrcu.be",
    "b1z.co"
];

export const FEATURE_NAMES = ['length_url', 'length_hostname', 'ip', 'nb_dots', 'nb_hyphens', 'nb_at', 'nb_qm', 'nb_and',
    'nb_or', 'nb_eq', 'nb_underscore', 'nb_tilde', 'nb_percent', 'nb_slash', 'nb_star', 'nb_colon',
    'nb_comma', 'nb_semicolumn', 'nb_dollar', 'nb_space', 'nb_dslash',
    'https_token', 'ratio_digits_url', 'ratio_digits_host', 'punycode',
    'nb_subdomains', 'prefix_suffix',
    'path_extension', 'length_words_raw', 'char_repeat', 'phish_hints',
    'shortest_words_raw', 'shortest_word_host', 'shortest_word_path', 'longest_words_raw',
    'longest_word_host', 'longest_word_path', 'avg_words_raw', 'avg_word_host', 'avg_word_path'
];

export const brands = (/sberbank|tinkoff|vtb|alfabank|raiffeisen|gazprombank|rosbank|ozon|wildberries|yandexmarket|market.yandex|citilink|mvideo|eldorado|yandex|mail|mail.ru|vk|vkontakte|rambler|megafon|mts|beeline|tele2|roscosmos|gosuslugi|nalog|pfr|mvd|mos|kremlin|pochta|cdek|boxberry|dpd|amazon|paypal|google|microsoft|apple|facebook|instagram|whatsapp|netflix|tesla|nike|adidas|samsung|huawei|sony|coca-cola|pepsi|mcdonalds|starbucks|burgerking|twitter|youtube|linkedin|ebay|alibaba|tiktok|snapchat|zoom|uber|lyft|airbnb|pinterest|walmart|target|costco|dell|hp|lenovo|nvidia|amd|intel|oracle|ibm|sap|salesforce|adobe|spotify|slack|github|bitbucket|dropbox|box|icloud|drive|onedrive|skype|outlook|hotmail|yahoo|baidu|jd|tencent|wechat|xiaomi|oppo|vivo|realme|poco|bmw|audi|mercedes|toyota|honda|ford|chevrolet|volkswagen|lexus|nissan|hyundai|kia|subaru|mazda|ferrari|lamborghini|porsche|bentley|rolls-royce|bugatti|telegram/);
